### ISSUE TITLE
About the middle dot

### ISSUE THREAD

**Issue by marcioAlmada** [marcioAlmada/yay#1]
The middle dot character `·` was used to draft the DSL.

It's commonly used to denote token type composition:

``` php
macro {
    swap ( T_VARIABLE·A , T_VARIABLE·B )
} >> {
    (list(T_VARIABLE·A, T_VARIABLE·B) = [T_VARIABLE·B, T_VARIABLE·A])
}
```

It's also being used as syntax sugar for layer matching `···`, which is very intuitive because it resembles ellipsis `...` without clashing with legit `T_ELLIPSIS` from variadics:

``` php
macro { guard (···condition) {···body} } >> {
    if (! (···condition)) {
        ···body
        throw new \GuardError("Guard error.");
    }
}

guard ($something < 3) {
    throw new \InvalidArgumentException('Something is out of bounds.');
}
```

But turns out it may not be a good idea as there's people using visible spaces on their text editors:

![banoy](https://cloud.githubusercontent.com/assets/227395/10052771/ee20e5e6-61fe-11e5-828b-0664e49dcea0.png)

Some people also reported It's not very easy to type on many keyboards.

But... what to use instead?

**Comment by huanga** [comment]
How about `•` (`0x2022` or `&bull`)?

The only argument I have for `•` is that on Mac OS X, using default U.S. English input, it can be inputted with `⎇` (alt/option, I always get confused when I see that symbol) + `8`, which is pretty trivial. Where as I have a hard time finding the key mapping for the middle dot currently used in spec.

**Comment by assertchris** [comment]
`→` is a favourite of mine...

**Comment by dzuelke** [comment]
> How about `•` (`0x2022` or `&bull;`)?

That's more visible than the mid-dot too!

**Comment by TazeTSchnitzel** [comment]
I like @huanga's suggestion because I'm also using OS X and Alt+8 also works on the British layout.

**Comment by bwoebi** [comment]
· is alt+shift+h for me, alt+8 yields {.

I have no way to directly input the bullet character from keyboard.

**Comment by marcioAlmada** [comment]
Reopened per community request.

- [ ] Pick a more ergonomic composition identifier (instead of middle dot `·`) before the DSL leaves draft state.

**Comment by TazeTSchnitzel** [comment]
Oh, I can actually type `·` with alt+shift+9 (British Mac layout).

@bwoebi: you can type `•` with alt+shift+$ on the Swiss German Mac layout, and with alt+ü on the German Mac layout, if you're using one of those.

**Comment by TazeTSchnitzel** [comment]
Oh, I can actually type `·` with alt+shift+9 (British Mac layout).

@bwoebi: you can type `•` with alt+shift+$ on the Swiss French and Swiss German Mac layouts, and with alt+ü on the German Mac layout.

**Comment by bwoebi** [comment]
• … indeed! Thanks for the hint :-)

**Comment by marcioAlmada** [comment]
ok, it looks like `@` is surprisingly a good candidate that won't create issues for any keyboard layout and won't clash with common valid syntax, AFAIK:

Instead of:

```php
# composition
T_STRING·name

# layering
···some_layer

# parser comb
·ls(
  ·token(T_STRING),
  ·token·(',')
)·label
```

We would have:

```php
# composition
T_STRING@name

# layering
@@@some_layer

# parser comb
ls@(
  token@(T_STRING),
  token@(',')
)@label
```

Also no one would write macros with `@` ... unless to elide the "shut up" operator itself :stuck_out_tongue:

```php
macro { @ } >> { }
```

Thoughts?

**Comment by marcioAlmada** [comment]
@TazeTSchnitzel @dzuelke the problem with @huanga's suggestion IMMO is that we would still have some demographics that wouldn't be able to type `•` easily (at least on my Pt-BR keyboard, on linux I still couldn't find the right keys to tap).

**Comment by TazeTSchnitzel** [comment]
Using @ would mean you couldn't use that in your own syntax.

**Comment by huanga** [comment]
I've been thinking more about the `•` character vs originally proposed `·` character. 

Both of them offers no clean universal way for input. Plus, each carries its own meaning in specific domains (`·` is used to denote "dot product" in the Mathematics domain, `•` is generally used to denote a list item), and so we will also need to offer proper escape characters to ensure they're usable in normal context.

On the other hand, `@` is pretty much universally the same (`shift + 2`), and even on other key mappings, due to the wide adoption of the symbol, it should almost always be printed and visible enough to not have to explain. If escaping is unavoidable anyway, and there's already a standard for escaping (`\`), then mandating the use of an escape to use the character in regular context would heavily tilt the favor towards something that is easy to type like `@`.

That said, I don't know how much complexity is added by requiring escape character to be used preceding the token, so that will be a separate research assignment for later ;)

**Comment by huanga** [comment]
Oops, I just realized why `@` might not be a good idea: http://php.net/manual/en/language.operators.errorcontrol.php

I'd have to withdraw my support for `@` for now, but the sentiment of finding something that is universally easy to type, and adding escape support in regular usage, still stands.

**Comment by novasdream** [comment]
maybe ¢ or ¬ or something like ._

**Comment by afaur** [comment]
I am okay with either · or • personally.

I am not sure what text editors everyone is using but I thought it would be worth mentioning here how to setup a shortcut for text expansion.

# Vim
- Edit `~/.vimrc`
- Add
```
inoremap <S-Tab> ·
```
- Press Shift + Tab and it will `·` character

# Sublime Text
- [Instructions](http://stackoverflow.com/questions/15582210/sublime-text-how-to-make-shortcut-for-inserting-text)

# Atom
- [Instructions](https://discuss.atom.io/t/how-to-create-key-binding-for-inserting-text-in-editor/21718/6#post_6)

**Comment by marcioAlmada** [comment]
Redirecting this discussion to #29

**Comment by icywolfy** [comment]
Needless to say, anything other than normal A-Z0-9 is not universally convenient.  (Even those require headache for anyone using a non-Latin language, where you're always switching keyboard layouts, or using caps-lock as a latin-toggle.

Now,  on US-English, Windows -- how does one type the middle dot?  Would I just have to copy-paste it everywhere?

**Comment by chris-kruining** [comment]
@icywolfy you could use the alt code (alt+0183 I believe)

**Comment by assertchris** [comment]
Should this be closed?

**Comment by marcioAlmada** [comment]
Yes. Closing.
