### ISSUE TITLE
Allow to control trailing tokens when doing layer unpacking

### ISSUE THREAD

**Issue by sekjun9878** [marcioAlmada/yay#21]
In a macro expansion such as
```
function (·vars ··· { ·var , }) { return ·expr; }
```
It is impossible to specify the correct amount of commas (to my knowledge of YAY functionality) - the last match will always add a trailing comma which is invalid syntax.

On function calls this can be alleviated by using array destructuring ...[var, var, var, ] but function definitions do not have this workaround.

**Comment by marcioAlmada** [comment]
This one is listed on the roadmap issue #3. Basically we need an expander called `·ls(·vars, ',', YAY_NO_TRAILING)` that would allow you to decide if a trailing separator (in your case a comma) should be added or not.

Or maybe we need syntax support on the current unpacking syntax to indicate how to make delimiters behave.

**Comment by marcioAlmada** [comment]
Expanders are declared here, btw https://github.com/marcioAlmada/yay/blob/master/src/expanders.php.

They are just functions that receive a `TokenStream` and return another `TokenStream`.

**Comment by sekjun9878** [comment]
@marcioAlmada What do you think about an IRC channel on freenode? Would you mind if I implemented some of the easy picks?

**Comment by marcioAlmada** [comment]
I'm currently in transit :airplane: so there won't be time to create a real time support channel withing the next 3 days. But feel free to get some easy picks. I'll try to reply ASAP.

**Comment by sekjun9878** [comment]
Ah okay. Safe travels!

**Comment by marcioAlmada** [comment]
`·implode(·vars, ',')` is probably more self explanatory.

**Comment by marcioAlmada** [comment]
Turns out adding first class trailing token control to the already existing unpacking syntax `···` look way more expressive. See the tests at  	e79505a.
