### ISSUE TITLE
Use PHPDoc to specify multiple returns in codebase

### ISSUE THREAD

**Issue by sekjun9878** [marcioAlmada/yay#24]
I noticed that you are currently using the notation of
```
function func() /* : Node|null */ {
```
to specify multliple returns, but this isn't detected by many static analysers and IDEs.

For proper type hinting and checking I propose that the format be modified to:
```
/**
 * @return Node|null
 */
function func() {
```
which is in compliance with the PHPDoc standards.

**Comment by marcioAlmada** [comment]
Hi,

This notation is actually a possibility for PHP 7.1, see https://wiki.php.net/rfc/union_types. I'd prefer to keep the "union return type" information as there is a WIP polyfill for this language feature [here](https://github.com/marcioAlmada/yay/blob/master/tests/phppt/primitive_union_return_types.phppt) and, long story short, there is an intent to **use the preprocessor to build itself** in the future.


But I'm 100% okay with having dockblocks too, when necessary, specially while "union return types" or "nullable return types" doesn't come.

**Comment by marcioAlmada** [comment]
Feel free to add a docblock whenever you see a `/* : <type>|<type>|... */` comment.
