### ISSUE TITLE
[RFC] Preprocessor Syntax

### ISSUE THREAD

**Issue by marcioAlmada** [marcioAlmada/yay#29]
# [RFC] Preprocessor Syntax

Community expressed difficulties with the middle dot syntax as it was considered not easy for everybody to type inter punctuation. Before proceeding with a more formal spec or working on a PHP engine extension / integration, we are going to do a few rounds of RFC in order for everybody to be able to voice an opinion.
## Current Syntax

Macro declarations are composed of 3 members - attributes list, pattern and expansion:

``` php
macro <attributes...> { <pattern> } >> { <expansion> }
```

Right now we have the following constructs on the pattern DSL:
- labeled tokens - Ex.: `T_STRING·label`
- labeled layer matching - Ex.: `{···label}` or `(···label)` or `[···label]`
- "complex" parsers - aka parser combinator API - Ex.: `·ls(·token(T_STRING)·identifier, ',')·list_of_identifiers` (matches a comma separated list of identifiers)

On the expansion DSL we have almost 100% symmetric constructs:
- labeled tokens deconstruction - Ex.: `T_STRING·label`
- labeled layer deconstruction - Ex.: `{···label}` or `(···label)` or `[···label]`
- AST unpacking deconstruction - Ex.: `·list_of_identifiers ···(, ){·identifier}` (expands and enforests the identifiers from AST into some custom syntax according to the template within `{}`)

In practice the middle dot acts as a sigil to identify what belongs to the preprocessor. A more complex macro, like the one used to have [short functions](https://github.com/marcioAlmada/yay/blob/master/tests/phpt/short_functions.phpt), looks like this:

``` php
macro ·recursion {
    fn // matches literal 'fn'
    (
        ·ls
        (
            ·chain
            (
                ·optional(·ns()·type)
                ,
                ·token(T_VARIABLE)·arg_name
            )
            ·arg
            ,
            ·token(',')
        )
        ·args
    )

    ·optional
    (
        ·chain
        (
            ·token(':')
            ,
            ·ns()
        )
    )
    ·return_type

    ~> // matches literal 'swimming' arrow operator '~>'

    (···body)

} >> {
    (function ($context){
        return function (·args ···(, ){ ·arg ···{·type ·arg_name}}) use($context) ·return_type {
            extract($context);
            return ···body;
        };
    })(get_defined_vars())
}
```
## Possible New Syntax

An alternative syntax could use `$()` as the pre processor's sigil, instead of the middle dots:

We would have the following constructs on the pattern DSL:
- labeled tokens - Ex.: `$(T_STRING as label)`
- labeled layer matching - Ex.: `$((...label))` or `$({...label})` or `$([...label])`
- "complex" parsers - aka parser combinator API - Ex.: `$(ls(token(T_STRING) as identifier, ',') as list_of_identifiers` (matches a comma separated list of identifiers)

On the expansion DSL we would still have almost 100% symmetric constructs:
- labeled tokens deconstruction - Ex.: `$(label)`
- labeled layer deconstruction - Ex.: `$((...label))` or `$({...label})` or `$([...label])`
- AST unpacking deconstruction - Ex.: `$(...list_of_identifiers)(, ){$(identifier)}` (expands and enforests the identifiers from AST into some custom syntax according to the template within `{}`)

A port of the short lambda macro, from above, would be:

``` php
$(macro recursion) {
    fn // matches literal 'fn'
    (
        $(
            ls(
                chain
                (
                    optional
                    (
                        ns() as type
                    ),
                    token(T_VARIABLE) as arg
                )
                ,
                token(',')
            )
            as args
        )
    )

    $(
        optional
        (
            chain
            (
                token(':')
                ,
                ns()
            )
        )
        as return_type
    )

    ~> // matches literal 'swimming' arrow operator '~>'

    $((...body))

} >> {
    (function ($context){
        return function ($(...args)(, ){ $(...arg){$(type) $(arg)}}) use($context) $(return_type) {
            extract($context);
            return $((...body));
        };
    })(get_defined_vars())
}
```

> Beware the great amount of white space is optional

This looks more verbose, but it's still unambiguous and easy to type compared to the syntax with interpunctuation. Thoughts?

**Comment by chris-kruining** [comment]
if this discussion is still open I'd like to propse to use the `~`, as far as I'm aware this character is not used in php (checked based on memory and [this list](https://www.w3schools.com/php/php_operators.asp))

**Comment by chris-kruining** [comment]
ooooh of cource my bad :S Should have known, oooh oooh ooh, does it need to be a single character per see or could we use a combination, for example `_>` or `//`. I wouldn't mind having to type a combination, am used to it after all `->`

**Comment by marcioAlmada** [comment]
@chris-kruining if it's "universally" easy to type and looks ergonomic enough it's a candidate. It seems to me that `_>` doesn't seem much superior to `$()`, or maybe I'm missing something.

**Comment by haskellcamargo** [comment]
I don't like the `$(` syntax. It seems confuse because PHP variables already use `$` and it requires parentheses everywhere (and thus parentheses terminators!). I believe that anything with more than 1 character could be a potential problem.

### Suggestions

`#`: it could be a problem because of single-line comments, however, but would be similar to C
`\`: it is not used as an isolated operator, but maybe they would conflict with namespaces

I still prefer using `\` (but keeping `·` as an alias, please), I just don't like how `···` would become `\\\`.

### Example

```php
macro \recursion {
    fn // matches literal 'fn'
    (
        \ls
        (
            \chain
            (
                \optional(\ns()\type)
                ,
                \token(T_VARIABLE)\arg_name
            )
            \arg
            ,
            \token(',')
        )
        \args
    )

    \optional
    (
        \chain
        (
            \token(':')
            ,
            \ns()
        )
    )
    \return_type

    ~> // matches literal 'swimming' arrow operator '~>'

    (\\\body)

} >> {
    (function ($context){
        return function (\args \\\(, ){ \arg \\\{\type \arg_name}}) use($context) \return_type {
            extract($context);
            return \\\body;
        };
    })(get_defined_vars())
}
```

**Comment by icywolfy** [comment]
Backslash would conflict with namespaced functions, or accessing globally defined functions.
return \extract($context) for when I want to use the global extract function over the locally defined namespace version.  Same with directly accessing \Exception without an import/re-alias. 

I would vote for "(#" and "#)" or "#(" ... ")" for a parsing mode change, to avoid a ton of prefix characters. (I agree with $ being too common for PHP code already)

And vote for #ls  #...   to match C-style pre-processors.  
Using # for comments in PHP comments is out of favour, and most do include a space "# inline comment"  so the conflict would be minimal.

**Comment by marcioAlmada** [comment]
After this long, I'm still very inclined to use `$()` as the sigil to substitute the current interpunctuation syntax.

**Comment by marcioAlmada** [comment]
Docs are coming on another PR.
