### ISSUE TITLE
How to solve? Arrow functions attempt.

### ISSUE THREAD

**Issue by chris-kruining** [marcioAlmada/yay#43]
Hey,

On [here](https://github.com/preprocess/pre-short-closures/issues/4) we're trying to solve a particlular case of syntax

What we are tying to achieve is ES6'esc arrow functions, which is basically syntax sugar for closures.
Given the following cases:

- ```$foo => strlen($foo) ```
- ```($foo, $bar) => $foo . $bar ```
- ```(string $foo, string $bar) : string => $foo . $bar ```
- ```($foo, $bar) => { return $foo . $bar; } ```

would all need to be parsed to
```php
function([[arguments]]): [[return type]] { return [[function body]]}
```

the `=>` as separator is just an example here since I 'copied' the ES6 syntax, feel free to use whatever to solve collisions with valid PHP

Is it possible to write 1/many macro's to solve this case? if so, how? if not, how can we?

Many thanks in advance!!!

**Comment by haskellcamargo** [comment]
Hi! [In this issue](https://github.com/marcioAlmada/yay/issues/29), we have been discussing about the syntax of Yay using arrow functions in the example. I think that may be useful.

**Comment by chris-kruining** [comment]
@haskellcamargo how so? that discussion is about the macro syntax is it not? I'm looking for a solution for implementing a macro that could solve syntax with optional delimiters.

**Comment by marcioAlmada** [comment]
@chris-kruining such feature would depend heavily on the `·expression()` parser feature (https://github.com/marcioAlmada/yay/pull/42), so matching the ES6 short closure syntax would be as simple as:

```php
macro ·global ·recursion {
    // the arglist as in $foo => ... or ($foo, $bar) => ...
    ·either(
        ·token(T_VARIABLE),
        ·chain(·token('('), ·optional(·ls(·token(T_VARIABLE)·arg_name), ·token(',')))·args ·token(')'))
    )
    // the optional return type
    ·optional(·chain(·token(':'), ·either(·ns(), ·rtoken('#^\w+$#'))))·return_type 
    // the arrow
    =>  
    // the body
   ·expression()·body
} >> {
   // the expansion thing
}
```

The lexical scoping part could be implemented using a midrule like so +  a more complicated expansion to circumvent PHP's limitations on not having lexical scoping built in:

```php

macro ·global ·recursion {
    // the arglist as in $foo => ... or ($foo, $bar) => ...
    ·either(
        ·token(T_VARIABLE),
        ·chain(·token('('), ·optional(·ls(·token(T_VARIABLE)·arg_name), ·token(',')))·args ·token(')'))
    )
    // the optional return type
    ·optional(·chain(·token(':'), ·either(·ns(), ·rtoken('#^\w+$#'))))·return_type 
    // the arrow
    =>  
    // the body
   ·expression()·body
}
>> function($ast) {
    $defined = [];
    foreach ($ast->{'·args'} as $node) $defined[(string) $node['·arg']['·arg_name']] = true;

    $scoped = [];
    $scope = new \Yay\Ast('·scope');
    foreach ($ast->{'···body'} as $token) {
        if (
            $token->is(T_VARIABLE) &&
            ('$this' !== (string) $token) &&
            false === isset($defined[(string) $token]) &&
            false === isset($scoped[(string) $token])
        ){
            $scope->push(new \Yay\Ast('·var', $token));
            $scoped[(string) $token] = true;
        }
    }

    $ast->append($scope);
}
>> {
    ·scope ?·{
        [
        ·scope ···(, ) { ·var = ·var ?? null},
        'short_closure' => function (·args ···(, ){ ·arg ···{·type ·arg_name}}) use(·scope ···(, ) { ·var }) ·return_type {
            ···body;
        }
        ]['short_closure']
    }
    ·scope !· {
        function (·args ···(, ){ ·arg ···{·type ·arg_name}}) ·return_type {
            ···body;
        }
    }
}
```

A variation of this with a different syntax, using `==>` instead of `=>` and always requiring braces is on the tests folder https://github.com/marcioAlmada/yay/blob/master/tests/phpt/short_functions_with_lexical_scope.phpt just beware it's just an automated test, not a production ready macro.

**Comment by marcioAlmada** [comment]
There is intent to work on the expression parser feature, but I am not having much time lately.

**Comment by marcioAlmada** [comment]
Done. Please refer to https://github.com/marcioAlmada/yay/commit/2ff980b7ad4496f21059cff30050188976c5ab02 for a solution.
