### ISSUE TITLE
Proposal: parser for function modifiers

### ISSUE THREAD

**Issue by assertchris** [marcioAlmada/yay#52]
Do you think it would be a good idea to add a parser for something like this?

```
optional(
    repeat(
        either(
            token(T_PUBLIC),
            token(T_PROTECTED),
            token(T_PRIVATE),
            token(T_STATIC)
        )
    )
)
```

...and if so, how would you recommend I do this?

**Comment by marcioAlmada** [comment]
I think it's fine to add this as a new function at `parsers.php`:

```php
function method_modifiers(): Parser {
	return optional(
	    repeat(
	        either(
	            token(T_PUBLIC),
	            token(T_PROTECTED),
	            token(T_PRIVATE),
	            token(T_STATIC)
	        )
	    )
	);
}
```

You may or may not add a check for duplicated modifiers as in:

```php
public public static function bar() // [...]
```

**Comment by marcioAlmada** [comment]
Actually, nevermind about the extra checks. It seems PHP goes for a compilation error rather than a syntax error https://3v4l.org/ZZJpB. And the same goes for contradictory modifiers as in `private public foo()`.

**Comment by assertchris** [comment]
Ok, I'll make a PR for this and some tests.

**Comment by assertchris** [comment]
Going to submit as PR if I get a solution that looks good.
