### ISSUE TITLE
Proposal: parser for function parameters

### ISSUE THREAD

**Issue by assertchris** [marcioAlmada/yay#53]
Do you think it would be a good idea to add a parser for something like this?

```
optional(either(
    ns(),
    token(T_ARRAY)
)),
token(T_VARIABLE),
optional(chain(
    token("="),
    expression()
))
```

...and if so, how would you recommend I do this?

**Comment by marcioAlmada** [comment]
LGTM me :+1:  we could add it as a new function at `parsers.php`. Usually this entity is named `arglist` in the PHP core.

**Comment by assertchris** [comment]
would you prefer I made it with the ls or without?

**Comment by marcioAlmada** [comment]
I thought it would be nice to have both `arg` and `arglist`.

**Comment by assertchris** [comment]
Going to submit as PR if I get a solution that looks good.
