### ISSUE TITLE
Can't alias in custom parser

### ISSUE THREAD

**Issue by assertchris** [marcioAlmada/yay#56]
I'm seeing a strange bug, and the best way I could think of to explain it is with a video...

[![Can't alias in custom parser (video)](https://img.youtube.com/vi/KajE01sSRb0/0.jpg)](https://www.youtube.com/watch?v=KajE01sSRb0)

As mentioned in the video, this problem disappears when the aliased parser is more deeply nested.

**Comment by assertchris** [comment]
Ok! I think I've narrowed the problem down.

1. It doesn't seem to matter whether or not the custom parsers are in the Yay namespace or not
2. It works when I use a custom parser with a custom expander:

```php
$(macro) {
    $(\Pre\Standard\Parser\argument())
} >> {
    $$(\Pre\Standard\Expander\argument($(argument)))
}
```

3. It doesn't work when I try and expand an AST in the expander block:

```php
$(macro) {
    // https://github.com/marcioAlmada/yay/issues/56
    $(\Pre\Standard\Parser\argument() as alias)
} >> {
    $(alias ... {
        ...
```

**Comment by marcioAlmada** [comment]
Hello. Any news?

**Comment by assertchris** [comment]
Will check with the newest master.

**Comment by assertchris** [comment]
Don't see this happening anymore.
