### ISSUE TITLE
Suggestion: Make AST mutable

### ISSUE THREAD

**Issue by assertchris** [marcioAlmada/yay#57]
After recent work on a generics macro, it occurs to me that being able to mutate `$ast` (in the compiler step) makes it significantly easier to build complex macros. [Here's where I am doing it...](https://github.com/preprocess/pre-generics/blob/master/source/macros.yay#L99-L103)

If I wasn't able to mutate the AST in this way, I doubt I would ever have come up with a working implementation. It could probably be made more efficiently, semantically closer to how macros work in other languages, and in more idiomatic PHP code; but it works because I don't have to re-create the AST to remove tokens from it that shouldn't appear in the transformed code.

**Comment by assertchris** [comment]
This is now possible with https://github.com/marcioAlmada/yay/commit/58556ccc676740f1e4397d546e192d032726e878

**Comment by marcioAlmada** [comment]
- [x] get capabilities
- [x] set capabilities
- [ ] unset capabilities (can be done with`$ast->{'something deep'} = null` but not equivalent to unset)

**Comment by chris-kruining** [comment]
@marcioAlmada Is it possible for the Ast to utilise ArrayAccess? because that would give you a mechanism to get, set, isset and unset

meaning `$ast->{'something deep'} = null` would become `unset($ast['something deep'])`.

I have no clue what repercussions this will have, just trying to help :P
