### ISSUE TITLE
Suggestion: Death to _()

### ISSUE THREAD

**Issue by assertchris** [marcioAlmada/yay#58]
It seems silly that we have to add placeholders (which have to be populated in the compiler step anyway) before they can be used in the translated code. If [the AST becomes mutable](https://github.com/marcioAlmada/yay/issues/57), wouldn't it be possible to automatically add the placeholders to the AST as the AST is mutated, so that they are usable in the translation step without needing to be defined in the match step?

**Comment by marcioAlmada** [comment]
I think we don't need this `_()` hack anymore after the static analysis part was removed from expansion parsing some time ago.

**Comment by assertchris** [comment]
Yeah, also effortless to insert them with the AST mutation we now have.
