### ISSUE TITLE
Suspicious Dockerfile

### ISSUE THREAD

**Issue by e1himself** [marcioAlmada/yay#71]
I can see this repo does have a Dockerfile (added with 6c138058)

But its contents seem to be unrelated to the repo purpose. Was it a mistake committing it?

https://github.com/marcioAlmada/yay/blob/6c138058a871cc73cbb76a6a04637e31a72bb689/Dockerfile#L1-L27

**Comment by marcioAlmada** [comment]
Wow! This is weird. I'm going to revoke all access tokens in the repo and my github account and clear this file from the history.
